name: Feedly Notifier
title: Feedly Notifier
description: Browser extension for reading news from RSS aggregator Feedly
url: https://olsh.github.io
enforce_ssl: olsh.github.io
baseurl: /Feedly-Notifier
markdown: kramdown
theme: jekyll-theme-cayman
show_downloads: false
